/**
 * SellerAI 서비스 SEO 데이터 (ARMES SEO Core 어댑터).
 *
 * 엔진(core/)은 건드리지 않고, 이 파일의 데이터만으로 셀러AI의 모든 SEO가 자동 생성된다.
 * 다른 ARMES 서비스는 이 파일을 본떠 services/<service>.ts 를 새로 만든다(이번 범위 아님).
 *
 * 키워드는 검색량 추정(상/중/하) 대신 검색의도(informational/comparison/transactional/tool/brand)로 분류한다.
 * 이미지 SEO: 임시 이미지라도 파일명·alt·title·caption을 제대로 채운다. 실제 결과물만 같은 파일명으로 덮으면 SEO 구조 유지.
 */
import type { ServiceSeoConfig, SeoFeature } from '@/lib/seo/core/types'

export const SELLERAI_SITE = 'https://www.armes.co.kr/sellerai'

// 내부링크·sitemap 순서 (메뉴 흐름과 동일)
const ORDER = [
  'home', 'model-select', 'dressed', 'product-only', 'translate',
  'remove-bg', 'color', 'detail-page', 'brand', 'pricing',
]

const FEATURES: Record<string, SeoFeature> = {
  // ===================== 메인 =====================
  home: {
    key: 'home', slug: '/studio', breadcrumb: '셀러AI',
    title: 'AI 상품사진·모델컷·상세페이지 자동화',
    description: '상품 사진 한 장으로 AI 모델컷·상품사진·누끼·상세페이지·1688 번역까지 자동 제작. 쇼핑몰 셀러를 위한 AI 상품 이미지 자동화 플랫폼 셀러AI.',
    keywords: [
      { term: 'AI 상품사진', intent: 'tool', role: 'primary' },
      { term: 'AI 모델컷', intent: 'tool', role: 'secondary' },
      { term: 'AI 상세페이지', intent: 'tool', role: 'secondary' },
      { term: 'AI 누끼', intent: 'tool', role: 'secondary' },
      { term: '쇼핑몰 상품 이미지 자동화', intent: 'informational', role: 'secondary' },
      { term: '쇼핑몰 상품 이미지 AI로 만들기', intent: 'informational', role: 'longtail' },
      { term: '1688 번역', intent: 'tool', role: 'longtail' },
    ],
    h1: 'AI 상품사진·모델컷 자동화', priority: 1.0,
    intro: {
      question: 'AI 상품사진·모델컷·상세페이지, 촬영 없이 한 곳에서 되나요?',
      problem: '쇼핑몰을 운영하면 상품마다 사진 촬영, AI 모델컷, 배경 정리(누끼), 색상 옵션, 상세페이지, 1688 외국어 번역까지 손이 갑니다. 각각 다른 도구를 쓰면 시간과 비용이 흩어집니다.',
      solution: '셀러AI는 상품 사진 한 장으로 AI 상품사진·AI 모델컷·AI 누끼·색상 옵션·AI 상세페이지·1688 번역까지 한 곳에서 만듭니다. 쇼핑몰 셀러를 위한 상품 이미지 자동화 도구로, 이미지 작업에 쓰는 시간을 줄이도록 기능을 모았습니다.',
    },
    useCases: ['AI 모델컷', 'AI 상품사진', 'AI 누끼·배경제거', '상품 색상 변경', '상세페이지 제작', '1688·알리 번역'],
    faq: [
      { q: '셀러AI는 무엇을 하는 서비스인가요?', a: '쇼핑몰 셀러를 위한 AI 상품 이미지 도구로, 모델컷·상품사진·누끼·상세페이지·외국어 번역을 한 곳에서 만듭니다.' },
      { q: '어떤 기능이 있나요?', a: 'AI 모델 생성, 착용샷, 상품사진, 배경제거, 색상 변경, 상세페이지 제작, 1688·알리 번역 등을 제공합니다.' },
      { q: '무료로 사용해 볼 수 있나요?', a: '가입 후 제공되는 이용권으로 주요 기능을 먼저 사용해 볼 수 있습니다.' },
      { q: '쿠팡·스마트스토어에 바로 쓸 수 있나요?', a: '쇼핑몰에 올릴 수 있는 형태의 이미지·상세페이지로 만들어집니다.' },
      { q: '디자인을 못 해도 쓸 수 있나요?', a: '사진을 올리고 옵션을 고르면 결과가 자동으로 만들어져 디자인 지식 없이 사용할 수 있습니다.' },
      { q: '만든 이미지를 상업적으로 사용해도 되나요?', a: '쇼핑몰 상품 판매용으로 사용하도록 만들어집니다.' },
      { q: '어떤 상품에 쓸 수 있나요?', a: '의류·가방·신발·뷰티·생활용품 등 다양한 상품 이미지에 사용할 수 있습니다.' },
      { q: '중국 도매 상품 이미지도 되나요?', a: '1688·알리·타오바오 상세페이지의 외국어를 한국어로 번역해 사용할 수 있습니다.' },
      { q: 'AI 모델의 초상권은 괜찮나요?', a: '실존 인물이 아닌 AI 모델이라 초상권 부담 없이 사용할 수 있습니다.' },
      { q: '이용권(토큰)은 어떻게 차감되나요?', a: '기능을 사용해 이미지를 만들 때 사진 단위로 이용권이 차감되며, 플랜별 제공량 안에서 사용합니다.' },
    ],
    related: ['product-only', 'model-select', 'translate', 'remove-bg', 'detail-page'],
  },

  // ===================== 1688 번역 (레퍼런스 — 완성) =====================
  translate: {
    key: 'translate', slug: '/studio/translate', guideSlug: '1688-translation', breadcrumb: '1688·알리 상세페이지 번역',
    title: '1688·알리 상세페이지 번역 | 중국어 이미지 번역',
    description: '1688·알리·타오바오 상세페이지의 중국어·영어 글자를 한국어로 자동 교체. 상품 이미지 속 외국어를 그대로 번역해 한글 상세페이지로 만드는 셀러AI 외국어 변환.',
    keywords: [
      { term: '1688 번역', intent: 'tool', role: 'primary' },
      { term: '알리 상세페이지 번역', intent: 'tool', role: 'secondary' },
      { term: '타오바오 번역', intent: 'tool', role: 'secondary' },
      { term: '중국어 이미지 번역', intent: 'tool', role: 'secondary' },
      { term: '1688 상세페이지 번역하는 방법', intent: 'informational', role: 'longtail' },
      { term: '상품 이미지 번역', intent: 'tool', role: 'longtail' },
      { term: '상세페이지 번역', intent: 'tool', role: 'longtail' },
      { term: '영어 이미지 번역', intent: 'tool', role: 'longtail' },
      { term: 'OCR 번역', intent: 'informational', role: 'longtail' },
    ],
    h1: '1688·알리 상세페이지 번역',
    ogTitle: '1688·알리 상세페이지 번역 — 중국어 이미지 그대로 한글로',
    ogDescription: '상품 이미지 속 중국어·영어를 한국어로 자동 교체. 글자 위치·디자인은 유지하고 문구만 한글화.',
    ogImage: '/seo/translate/1688-translate-hero-after.webp',
    priority: 0.9,
    intro: {
      question: '1688·알리·타오바오 상세페이지, 한글로 어떻게 번역하나요?',
      problem: '중국 도매 사이트에서 가져온 상품을 국내에 팔려면 상세페이지의 중국어·영어 글자를 한글로 바꿔야 합니다. 그런데 글자가 이미지 안에 그림처럼 박혀 있어 일반 번역기로는 바꿀 수 없고, 캡처해서 포토샵으로 일일이 지우고 다시 쓰면 한 장에 수십 분이 걸립니다.',
      solution: '셀러AI 외국어 변환은 이미지 속 외국어 글자를 자동으로 찾아 자연스러운 한국어로 교체합니다. 글자의 위치·크기·디자인은 그대로 두고 문구만 한글로 바꿔, 중국 상세페이지를 그대로 국내 판매용으로 만듭니다. 수영복·란제리처럼 직접 다듬어야 하는 사진은 브라우저 편집기에서 글자를 지우고 한글을 얹을 수 있습니다.',
    },
    steps: [
      { h3: '상품 이미지 올리기', desc: '번역할 1688·알리·타오바오 상세페이지 이미지를 최대 4장까지 올립니다.' },
      { h3: '번역 분석 (무료)', desc: '‘번역 분석’을 누르면 이미지 속 중국어·영어를 찾아 한국어 초안을 만들어 줍니다.' },
      { h3: '한글로 변환', desc: '번역 초안을 확인·수정한 뒤 변환하면 글자만 한글로 교체된 상세페이지가 완성됩니다.' },
    ],
    beforeAfter: [
      {
        label: '의류 상세페이지',
        before: { src: '/seo/translate/1688-translate-clothing-before.webp', alt: '1688 의류 상세페이지 중국어 원본', title: '번역 전 — 중국어 상세페이지', caption: '번역 전: 1688 의류 상세페이지의 중국어 문구' },
        after: { src: '/seo/translate/1688-translate-clothing-after.webp', alt: '의류 상세페이지 한국어 번역 결과', title: '번역 후 — 한글 상세페이지', caption: '번역 후: 같은 디자인에 한국어로 교체된 상세페이지' },
        description: '중국어로 된 의류 상세페이지의 문구를 한국어로 교체했습니다. 글자 위치와 레이아웃은 그대로 유지되어 바로 국내 쇼핑몰에 올릴 수 있습니다.',
      },
      {
        label: '수영복·란제리',
        before: { src: '/seo/translate/1688-translate-swimwear-before.webp', alt: '수영복 상세페이지 중국어 원본', title: '번역 전 — 수영복 상세페이지', caption: '번역 전: 수영복 상세페이지의 중국어 문구' },
        after: { src: '/seo/translate/1688-translate-swimwear-after.webp', alt: '수영복 상세페이지 한글 편집 결과', title: '번역 후 — 한글 편집', caption: '번역 후: 글자를 지우고 한글을 직접 얹은 수영복 상세페이지' },
        description: '수영복·란제리처럼 정교한 편집이 필요한 사진은 브라우저 편집기에서 외국어 글자를 지우고 한글 문구를 직접 배치할 수 있습니다.',
      },
      {
        label: '가방·잡화',
        before: { src: '/seo/translate/1688-translate-bag-before.webp', alt: '가방 상세페이지 중국어 원본', title: '번역 전 — 가방 상세페이지', caption: '번역 전: 가방 상세페이지의 중국어 문구' },
        after: { src: '/seo/translate/1688-translate-bag-after.webp', alt: '가방 상세페이지 한국어 번역 결과', title: '번역 후 — 한글 상세페이지', caption: '번역 후: 한국어로 교체된 가방 상세페이지' },
        description: '가방·잡화 상세페이지의 중국어 설명을 한국어로 바꿔, 제품 특징과 사이즈 안내를 국내 고객이 바로 이해할 수 있게 했습니다.',
      },
    ],
    useCases: ['의류 상세페이지', '수영복·란제리', '가방·잡화', '뷰티·생활용품', '타오바오 직구 상품'],
    faq: [
      { q: '1688 상세페이지를 한글로 번역하는 방법은?', a: '이미지를 올리고 ‘번역 분석’(무료)을 누르면 중국어·영어를 찾아 한국어 초안을 만들어 줍니다. 초안을 확인·수정한 뒤 변환하면 글자 위치와 디자인은 그대로 둔 채 문구만 한글로 교체됩니다. 포토샵 없이 3단계로 끝납니다.' },
      { q: '1688 상세페이지 번역이 정확한가요?', a: '이미지 속 중국어·영어를 찾아 한국어 초안을 만들어 주며, 변환 전에 번역 문구를 직접 확인하고 수정할 수 있습니다. 어색한 부분은 그대로 두지 않고 검수 단계에서 고친 뒤 변환하면 됩니다.' },
      { q: '번역한 상세페이지 이미지를 상업적으로 사용해도 되나요?', a: '직접 소싱한 상품의 상세페이지를 번역해 본인 쇼핑몰에 사용하는 용도로 만들어집니다. 원본 이미지의 저작권은 원 판매자에게 있으므로, 사용 권한이 있는 이미지에 한해 활용하시기 바랍니다.' },
      { q: '번역에 시간이 얼마나 걸리나요?', a: '이미지 한 장 기준 분석과 변환이 빠르게 진행됩니다. 한 번에 여러 장을 올려 함께 처리할 수 있습니다.' },
      { q: '어떤 언어를 지원하나요?', a: '중국어(간체)와 영어 등 상세페이지에 자주 쓰이는 외국어를 한국어로 교체합니다.' },
      { q: '글자 위치나 디자인이 그대로 유지되나요?', a: '글자의 위치·크기·배경 디자인은 유지하고 문구만 한국어로 바꾸기 때문에, 원본 상세페이지의 느낌을 그대로 살릴 수 있습니다.' },
      { q: '결과를 투명 PNG로 받을 수 있나요?', a: '번역 결과는 이미지 파일로 저장해 바로 상세페이지에 사용할 수 있습니다. 배경이 필요 없는 경우 배경제거(누끼) 기능과 함께 사용하면 됩니다.' },
      { q: '수영복·란제리 같은 사진도 번역할 수 있나요?', a: '가능합니다. 이런 상품은 브라우저 편집기에서 외국어 글자를 지우고 한글을 직접 얹어 더 자연스럽게 마무리할 수 있습니다.' },
      { q: '한 번에 몇 장까지 변환할 수 있나요?', a: '한 번에 최대 4장까지 올려 함께 번역·변환할 수 있습니다.' },
      { q: '이용권(토큰)은 얼마나 차감되나요?', a: '번역 분석은 무료이며, 한국어로 변환·완료할 때 사진 한 장당 이용권이 차감됩니다. 플랜별로 제공되는 이용권 안에서 사용합니다.' },
      { q: '타오바오·알리익스프레스 이미지도 되나요?', a: '1688뿐 아니라 타오바오·알리익스프레스 등에서 받은 상세페이지 이미지도 동일하게 한국어로 번역할 수 있습니다.' },
      { q: '번역 결과를 나중에 다시 수정할 수 있나요?', a: '번역 문구는 변환 전에 자유롭게 수정할 수 있고, 편집기에서는 글자 위치·글꼴·크기까지 직접 조정할 수 있습니다.' },
    ],
    related: ['remove-bg', 'product-only', 'detail-page', 'model-select'],
  },

  // ===================== AI 모델 생성 =====================
  'model-select': {
    key: 'model-select', slug: '/studio/create/model-select', guideSlug: 'ai-model', breadcrumb: 'AI 모델 생성',
    title: 'AI 모델 생성 | 쇼핑몰 AI 패션·피팅모델 만들기',
    description: '촬영 없이 AI 패션모델을 만들어 상품을 입혀보세요. 여성·남성·키즈 AI 모델로 쇼핑몰 모델컷과 피팅 이미지를 자동 생성하는 셀러AI 모델 생성.',
    keywords: [
      { term: 'AI 모델', intent: 'tool', role: 'primary' },
      { term: 'AI 모델 생성', intent: 'tool', role: 'secondary' },
      { term: '가상모델', intent: 'tool', role: 'secondary' },
      { term: 'AI 피팅모델', intent: 'tool', role: 'secondary' },
      { term: '쇼핑몰 모델', intent: 'tool', role: 'secondary' },
      { term: 'AI 쇼핑몰 모델 만드는 방법', intent: 'informational', role: 'longtail' },
      { term: 'AI 패션모델', intent: 'tool', role: 'longtail' },
      { term: 'AI 여성모델', intent: 'tool', role: 'longtail' },
      { term: 'AI 남성모델', intent: 'tool', role: 'longtail' },
      { term: 'AI 키즈모델', intent: 'tool', role: 'longtail' },
    ],
    h1: 'AI 모델 생성 — 여성·남성·키즈', priority: 0.9,
    intro: {
      question: '쇼핑몰 상품에 입힐 모델, 촬영 없이 만들 수 있나요?',
      problem: '모델 촬영은 모델 섭외, 스튜디오 대여, 일정 조율에 비용과 시간이 듭니다. 시즌마다 새 모델컷이 필요하고, 같은 모델을 계속 쓰기도 쉽지 않습니다.',
      solution: '셀러AI 모델 생성은 여성·남성·키즈 AI 모델 중에서 골라 상품에 어울리는 모델 이미지를 만듭니다. 실존 인물이 아닌 AI 모델이라 섭외나 초상권 부담 없이, 다양한 연령과 분위기의 모델을 반복해서 사용할 수 있습니다.',
    },
    steps: [
      { h3: '모델 선택', desc: '여성·남성·키즈, 연령대와 분위기를 골라 기준 모델을 정합니다.' },
      { h3: '상품·배경 설정', desc: '입힐 상품과 포즈·배경을 선택합니다.' },
      { h3: '모델컷 생성', desc: '선택한 조건으로 AI 모델이 상품을 착용한 이미지를 생성합니다.' },
    ],
    beforeAfter: [
      { label: '여성 모델컷',
        before: { src: '/seo/model-select/model-select-woman-before.webp', alt: '상품 단독 이미지', title: '모델 적용 전 — 상품 사진', caption: '적용 전: 상품만 있는 사진' },
        after: { src: '/seo/model-select/model-select-woman-after.webp', alt: 'AI 여성 모델 착용 이미지', title: '모델 적용 후 — AI 여성 모델', caption: '적용 후: AI 여성 모델이 착용한 모델컷' },
        description: '상품 사진에 AI 여성 모델을 적용해, 촬영 없이 쇼핑몰 모델컷을 만들었습니다.' },
      { label: '키즈 모델컷',
        before: { src: '/seo/model-select/model-select-kids-before.webp', alt: '아동복 단독 이미지', title: '모델 적용 전 — 아동복 사진', caption: '적용 전: 아동복 상품 사진' },
        after: { src: '/seo/model-select/model-select-kids-after.webp', alt: 'AI 키즈 모델 착용 이미지', title: '모델 적용 후 — AI 키즈 모델', caption: '적용 후: AI 키즈 모델 착용 컷' },
        description: '아동복은 AI 키즈 모델로 연령대에 맞는 모델컷을 만들 수 있습니다.' },
    ],
    useCases: ['여성 의류', '남성 의류', '아동복', '액세서리', '언더웨어'],
    faq: [
      { q: 'AI 쇼핑몰 모델 만드는 방법은?', a: '여성·남성·키즈 중 모델을 고르고, 입힐 상품과 포즈·배경을 선택한 뒤 생성하면 AI 모델이 상품을 착용한 모델컷이 만들어집니다. 실존 인물이 아니라 초상권 부담 없이 여러 번 만들어 마음에 드는 컷을 고를 수 있습니다.' },
      { q: 'AI 모델이 자연스럽게 나오나요?', a: '얼굴·체형·포즈가 상품에 맞게 생성되며, 여러 번 생성해 마음에 드는 컷을 고를 수 있습니다.' },
      { q: '같은 모델을 계속 사용할 수 있나요?', a: '기준 모델을 정해 두면 동일한 느낌의 모델로 여러 상품 컷을 이어서 만들 수 있습니다.' },
      { q: 'AI 모델 이미지를 상업적으로 사용해도 되나요?', a: '쇼핑몰 상품 판매용 모델컷으로 사용하도록 만들어집니다.' },
      { q: '실존 인물과 초상권 문제는 없나요?', a: 'AI로 생성한 가상 모델이라 실존 인물이 아니며, 모델 섭외·초상권 부담 없이 사용할 수 있습니다.' },
      { q: '키즈 모델도 만들 수 있나요?', a: '아동복에 맞는 키즈 모델을 연령대별로 선택할 수 있습니다.' },
      { q: '남성 모델도 지원하나요?', a: '여성·남성·키즈 모델을 모두 지원합니다.' },
      { q: '모델 얼굴을 다양하게 바꿀 수 있나요?', a: '분위기와 연령대를 바꿔 다양한 얼굴의 모델을 생성할 수 있습니다.' },
      { q: '포즈나 배경도 고를 수 있나요?', a: '포즈와 배경을 선택해 상품에 어울리는 모델컷을 만들 수 있습니다.' },
      { q: '이용권(토큰)은 어떻게 차감되나요?', a: '이미지를 생성할 때 사진 단위로 이용권이 차감되며, 플랜별 제공 이용권 안에서 사용합니다.' },
      { q: '만든 모델컷은 어디에 저장되나요?', a: '생성한 이미지는 보관함에 저장되어 다시 내려받을 수 있습니다.' },
    ],
    related: ['dressed', 'detail-page', 'product-only', 'brand'],
  },

  // ===================== AI 착용샷 =====================
  dressed: {
    key: 'dressed', slug: '/studio/create/dressed', guideSlug: 'outfit-fitting', breadcrumb: 'AI 착용샷·옷 합성',
    title: 'AI 착용샷·옷 합성 | 쇼핑몰 모델 착용컷 만들기',
    description: '옷·의류 사진을 AI 모델에게 입혀 자연스러운 착용샷·가상 피팅 이미지를 제작. 촬영 없이 쇼핑몰 모델컷·룩북을 만드는 AI 의류 합성 도구 셀러AI.',
    keywords: [
      { term: 'AI 착용샷', intent: 'tool', role: 'primary' },
      { term: '옷 합성', intent: 'tool', role: 'secondary' },
      { term: '가상 피팅', intent: 'tool', role: 'secondary' },
      { term: 'AI 의류 합성', intent: 'tool', role: 'secondary' },
      { term: '옷 사진 모델에게 입히는 방법', intent: 'informational', role: 'longtail' },
      { term: '쇼핑몰 착용컷', intent: 'tool', role: 'longtail' },
      { term: 'AI 피팅', intent: 'tool', role: 'longtail' },
      { term: '모델 착용사진', intent: 'tool', role: 'longtail' },
      { term: 'AI 룩북', intent: 'tool', role: 'longtail' },
    ],
    h1: 'AI 착용샷·옷 합성', priority: 0.9,
    intro: {
      question: '옷 사진을 모델이 입은 착용샷으로 만들 수 있나요?',
      problem: '옷만 찍은 사진은 실제 입었을 때의 핏과 느낌을 보여주기 어렵습니다. 그렇다고 모델을 불러 매번 촬영하면 비용과 일정 부담이 큽니다.',
      solution: '셀러AI 착용샷은 옷·의류 사진을 AI 모델에게 입혀 자연스러운 착용 이미지를 만듭니다. 촬영 없이 모델이 착용한 핏과 분위기를 보여줘 구매 결정을 돕는 모델컷·룩북을 제작할 수 있습니다.',
    },
    steps: [
      { h3: '의류 사진 올리기', desc: '착용샷으로 만들 옷·의류 사진을 올립니다.' },
      { h3: '모델·포즈 선택', desc: '옷에 어울리는 모델과 포즈를 고릅니다.' },
      { h3: '착용샷 생성', desc: 'AI가 옷을 모델에게 입힌 착용 이미지를 생성합니다.' },
    ],
    beforeAfter: [
      { label: '원피스 착용샷',
        before: { src: '/seo/dressed/dressed-onepiece-before.webp', alt: '원피스 단독 사진', title: '합성 전 — 원피스 사진', caption: '합성 전: 옷만 있는 사진' },
        after: { src: '/seo/dressed/dressed-onepiece-after.webp', alt: 'AI 모델 원피스 착용샷', title: '합성 후 — 착용샷', caption: '합성 후: 모델이 원피스를 입은 착용샷' },
        description: '원피스 사진을 AI 모델이 착용한 모습으로 바꿔, 실제 핏을 보여주는 착용샷을 만들었습니다.' },
      { label: '아우터 착용샷',
        before: { src: '/seo/dressed/dressed-outer-before.webp', alt: '아우터 단독 사진', title: '합성 전 — 아우터 사진', caption: '합성 전: 아우터 상품 사진' },
        after: { src: '/seo/dressed/dressed-outer-after.webp', alt: 'AI 모델 아우터 착용샷', title: '합성 후 — 착용샷', caption: '합성 후: 모델이 아우터를 입은 착용샷' },
        description: '아우터의 길이감과 실루엣을 모델 착용샷으로 보여줘 룩북에 바로 쓸 수 있습니다.' },
    ],
    useCases: ['원피스', '아우터·코트', '니트·티셔츠', '팬츠·스커트', '룩북 화보'],
    faq: [
      { q: '옷 사진을 모델 착용샷으로 만드는 방법은?', a: '착용샷으로 만들 옷·의류 사진을 올리고, 어울리는 모델과 포즈를 고른 뒤 생성하면 AI가 그 옷을 모델에게 입힌 착용 이미지를 만들어 줍니다. 모델을 바꿔 같은 옷의 여러 착용샷도 만들 수 있습니다.' },
      { q: '옷 사진만 있어도 착용샷이 되나요?', a: '옷·의류 사진을 올리면 AI 모델이 착용한 이미지로 만들어 줍니다.' },
      { q: '옷의 색이나 무늬가 그대로 유지되나요?', a: '원본 옷의 색상과 패턴을 살려 착용 모습으로 합성합니다.' },
      { q: '모델을 바꿔서 여러 착용샷을 만들 수 있나요?', a: '모델과 포즈를 바꿔 같은 옷의 다양한 착용샷을 만들 수 있습니다.' },
      { q: '룩북 용도로 써도 되나요?', a: '여러 착용샷을 모아 룩북이나 코디 화보로 활용할 수 있습니다.' },
      { q: '상의·하의·아우터 모두 되나요?', a: '원피스, 아우터, 상의, 하의 등 다양한 의류 종류를 지원합니다.' },
      { q: '실제 모델 촬영과 비교해 어떤 점이 좋나요?', a: '촬영 섭외와 비용 없이 빠르게 여러 컷을 만들 수 있다는 점이 다릅니다.' },
      { q: '포즈를 선택할 수 있나요?', a: '옷에 어울리는 포즈를 골라 착용샷을 만들 수 있습니다.' },
      { q: '초상권 문제는 없나요?', a: 'AI로 생성한 가상 모델이라 실존 인물이 아니며 초상권 부담이 없습니다.' },
      { q: '이용권(토큰)은 어떻게 차감되나요?', a: '착용샷을 생성할 때 사진 단위로 이용권이 차감됩니다.' },
      { q: '만든 착용샷은 저장되나요?', a: '생성한 착용샷은 보관함에 저장되어 다시 받을 수 있습니다.' },
    ],
    related: ['model-select', 'product-only', 'detail-page', 'brand'],
  },

  // ===================== AI 상품사진 =====================
  'product-only': {
    key: 'product-only', slug: '/studio/create/product-only', guideSlug: 'product-photo', breadcrumb: 'AI 상품사진',
    title: '상품사진 만들기·제품사진 제작 | 스튜디오 없이',
    description: '배경·조명 걱정 없이 AI가 깔끔한 상품 단독컷을 제작. 쇼핑몰 메인컷과 제품 이미지를 촬영 없이 만드는 AI 상품사진 도구 셀러AI.',
    keywords: [
      { term: '상품사진 만들기', intent: 'tool', role: 'primary' },
      { term: '제품사진', intent: 'tool', role: 'secondary' },
      { term: '쇼핑몰 상품사진', intent: 'tool', role: 'secondary' },
      { term: 'AI 상품사진', intent: 'tool', role: 'secondary' },
      { term: '스튜디오 없이 제품사진 만드는 법', intent: 'informational', role: 'longtail' },
      { term: '제품 촬영', intent: 'tool', role: 'longtail' },
      { term: '상품 메인컷', intent: 'tool', role: 'longtail' },
      { term: 'AI 제품촬영', intent: 'tool', role: 'longtail' },
    ],
    h1: 'AI 상품사진 만들기', priority: 0.9,
    intro: {
      question: '깔끔한 상품 사진, 스튜디오 없이 만들 수 있나요?',
      problem: '집에서 찍은 상품 사진은 배경이 지저분하거나 조명이 일정하지 않아 쇼핑몰 메인컷으로 쓰기 어렵습니다. 매번 스튜디오를 빌리기도 부담입니다.',
      solution: '셀러AI 상품사진은 올린 상품을 깔끔한 배경과 조명의 단독컷으로 만듭니다. 촬영 장비 없이 쇼핑몰 메인컷·썸네일에 바로 쓸 수 있는 제품 이미지를 만들 수 있습니다.',
    },
    steps: [
      { h3: '상품 사진 올리기', desc: '단독컷으로 만들 상품 사진을 올립니다.' },
      { h3: '배경·구도 선택', desc: '제품에 어울리는 배경과 구도를 고릅니다.' },
      { h3: '상품컷 생성', desc: 'AI가 깔끔한 상품 단독컷을 생성합니다.' },
    ],
    beforeAfter: [
      { label: '의류 상품컷',
        before: { src: '/seo/product-only/product-only-apparel-before.webp', alt: '정리되지 않은 의류 사진', title: '보정 전 — 의류 사진', caption: '보정 전: 배경이 정리되지 않은 사진' },
        after: { src: '/seo/product-only/product-only-apparel-after.webp', alt: '깔끔한 의류 상품컷', title: '보정 후 — 상품 단독컷', caption: '보정 후: 깔끔한 배경의 상품컷' },
        description: '의류 사진을 정돈된 배경의 상품 단독컷으로 만들어 메인컷으로 바로 사용할 수 있습니다.' },
      { label: '잡화 상품컷',
        before: { src: '/seo/product-only/product-only-goods-before.webp', alt: '잡화 일반 사진', title: '보정 전 — 잡화 사진', caption: '보정 전: 잡화 상품 사진' },
        after: { src: '/seo/product-only/product-only-goods-after.webp', alt: '깔끔한 잡화 상품컷', title: '보정 후 — 상품 단독컷', caption: '보정 후: 정돈된 잡화 상품컷' },
        description: '가방·소품 같은 잡화도 일정한 배경의 상품컷으로 만들어 쇼핑몰 톤을 통일할 수 있습니다.' },
    ],
    useCases: ['의류', '가방·잡화', '신발', '뷰티·소품', '생활용품'],
    faq: [
      { q: '스튜디오 없이 AI 상품사진 만드는 방법은?', a: '휴대폰으로 찍은 상품 사진을 올리고, 제품에 어울리는 배경과 구도를 고른 뒤 생성하면 깔끔한 배경·조명의 상품 단독컷이 만들어집니다. 촬영 장비나 스튜디오 없이 쇼핑몰 메인컷·썸네일을 바로 만들 수 있습니다.' },
      { q: '집에서 찍은 사진도 상품컷이 되나요?', a: '휴대폰으로 찍은 사진도 올리면 정돈된 배경의 상품 단독컷으로 만들어 줍니다.' },
      { q: '배경을 원하는 색으로 바꿀 수 있나요?', a: '제품에 어울리는 배경과 구도를 선택해 상품컷을 만들 수 있습니다.' },
      { q: '쿠팡·스마트스토어 메인컷으로 써도 되나요?', a: '쇼핑몰 메인컷·썸네일 용도로 사용할 수 있는 비율과 구도로 만들어집니다.' },
      { q: '상품 모양이 바뀌지는 않나요?', a: '원본 상품의 형태를 유지하면서 배경과 조명을 정돈합니다.' },
      { q: '여러 상품을 한 번에 만들 수 있나요?', a: '여러 장을 올려 같은 톤의 상품컷으로 만들 수 있습니다.' },
      { q: '누끼(투명 배경)도 같이 되나요?', a: '배경이 필요 없는 경우 배경제거 기능과 함께 사용하면 투명 PNG로 만들 수 있습니다.' },
      { q: '신발이나 가방도 되나요?', a: '의류뿐 아니라 신발·가방·소품 등 다양한 상품을 지원합니다.' },
      { q: '결과 비율을 정할 수 있나요?', a: '쇼핑몰에 맞는 정사각형·세로형 등 비율로 만들 수 있습니다.' },
      { q: '이용권(토큰)은 어떻게 차감되나요?', a: '상품컷을 생성할 때 사진 단위로 이용권이 차감됩니다.' },
      { q: '만든 상품컷은 저장되나요?', a: '생성한 이미지는 보관함에 저장되어 다시 받을 수 있습니다.' },
    ],
    related: ['remove-bg', 'model-select', 'detail-page', 'color'],
  },

  // ===================== AI 누끼·배경제거 =====================
  'remove-bg': {
    key: 'remove-bg', slug: '/studio/edit/remove-bg', guideSlug: 'remove-background', breadcrumb: 'AI 누끼·배경제거',
    title: '누끼 따기·사진 배경 제거 | 상품 사진 투명 PNG 만들기',
    description: '상품 사진 배경을 AI가 몇 초 만에 제거. 흰 배경·투명 PNG 누끼를 자동으로 만들어 쿠팡 썸네일과 쇼핑몰 메인컷에 바로 쓰는 셀러AI 배경제거.',
    keywords: [
      { term: '누끼 따기', intent: 'tool', role: 'primary' },
      { term: '배경 제거', intent: 'tool', role: 'secondary' },
      { term: '누끼 사이트', intent: 'tool', role: 'secondary' },
      { term: 'AI 누끼', intent: 'tool', role: 'secondary' },
      { term: '사진 배경 지우는 방법', intent: 'informational', role: 'longtail' },
      { term: '투명 PNG 만들기', intent: 'informational', role: 'longtail' },
      { term: '상품 누끼', intent: 'tool', role: 'longtail' },
      { term: '쇼핑몰 누끼', intent: 'tool', role: 'longtail' },
      { term: '이미지 배경제거', intent: 'tool', role: 'longtail' },
    ],
    h1: 'AI 누끼따기·배경제거', priority: 0.9,
    intro: {
      question: '상품 사진 배경, 어떻게 깔끔하게 지우나요?',
      problem: '쿠팡 썸네일은 흰 배경이 기본이고, 쇼핑몰 메인컷도 배경이 지저분하면 상품이 묻힙니다. 포토샵으로 일일이 따려면 시간이 오래 걸리고 경계가 거칠어지기 쉽습니다.',
      solution: '셀러AI 배경제거는 상품 사진의 배경을 AI가 자동으로 지워 깔끔한 누끼를 만듭니다. 흰 배경이나 투명 PNG로 받아 쿠팡 썸네일·쇼핑몰 메인컷에 바로 사용할 수 있습니다.',
    },
    steps: [
      { h3: '사진 올리기', desc: '배경을 지울 상품 사진을 올립니다.' },
      { h3: '배경 제거', desc: 'AI가 상품만 남기고 배경을 자동으로 지웁니다.' },
      { h3: '저장', desc: '흰 배경 또는 투명 PNG로 저장해 바로 사용합니다.' },
    ],
    beforeAfter: [
      { label: '의류 누끼',
        before: { src: '/seo/remove-bg/remove-bg-apparel-before.webp', alt: '배경 있는 의류 사진', title: '제거 전 — 배경 있는 사진', caption: '제거 전: 배경이 있는 의류 사진' },
        after: { src: '/seo/remove-bg/remove-bg-apparel-after.webp', alt: '배경 제거된 의류 누끼', title: '제거 후 — 누끼 이미지', caption: '제거 후: 배경을 지운 의류 누끼' },
        description: '의류 사진의 배경을 지워 쿠팡 썸네일용 흰 배경·투명 누끼로 만들었습니다.' },
      { label: '잡화 누끼',
        before: { src: '/seo/remove-bg/remove-bg-goods-before.webp', alt: '배경 있는 잡화 사진', title: '제거 전 — 배경 있는 사진', caption: '제거 전: 배경이 있는 잡화 사진' },
        after: { src: '/seo/remove-bg/remove-bg-goods-after.webp', alt: '배경 제거된 잡화 누끼', title: '제거 후 — 누끼 이미지', caption: '제거 후: 배경을 지운 잡화 누끼' },
        description: '가방·소품의 배경을 깔끔하게 제거해 메인컷과 옵션 이미지를 통일했습니다.' },
    ],
    useCases: ['쿠팡 썸네일', '의류 누끼', '가방·신발 누끼', '소품·액세서리', '투명 PNG 소재'],
    faq: [
      { q: '사진 배경을 지우고 누끼 따는 방법은?', a: '배경을 지울 상품 사진을 올리면 AI가 상품만 남기고 배경을 자동으로 지웁니다. 결과는 흰 배경이나 투명 PNG로 저장할 수 있어, 포토샵 없이 쿠팡 썸네일·쇼핑몰 메인컷에 바로 쓸 수 있습니다.' },
      { q: '배경제거가 얼마나 깔끔한가요?', a: 'AI가 상품의 경계를 따라 배경을 지워 머리카락·손잡이 같은 가는 부분도 자연스럽게 처리합니다.' },
      { q: '투명 PNG로 받을 수 있나요?', a: '배경이 투명한 PNG로 저장할 수 있어 다른 배경 위에 바로 올릴 수 있습니다.' },
      { q: '흰 배경으로도 만들 수 있나요?', a: '쿠팡 썸네일에 맞는 흰 배경으로도 만들 수 있습니다.' },
      { q: '여러 장을 한 번에 처리할 수 있나요?', a: '여러 사진을 올려 배경을 한 번에 제거할 수 있습니다.' },
      { q: '상품 일부가 같이 지워지지 않나요?', a: '상품 영역을 인식해 제거하며, 결과를 확인하고 다시 처리할 수 있습니다.' },
      { q: '복잡한 배경도 되나요?', a: '배경이 복잡한 사진도 상품을 분리해 누끼를 만듭니다.' },
      { q: '신발·가방도 되나요?', a: '의류뿐 아니라 신발·가방·소품 등 다양한 상품을 지원합니다.' },
      { q: '누끼 후 다른 배경을 넣을 수 있나요?', a: '투명 PNG로 받아 상품사진 기능 등에서 원하는 배경에 올릴 수 있습니다.' },
      { q: '이용권(토큰)은 어떻게 차감되나요?', a: '배경을 제거할 때 사진 단위로 이용권이 차감됩니다.' },
      { q: '결과는 저장되나요?', a: '처리한 누끼 이미지는 보관함에 저장되어 다시 받을 수 있습니다.' },
    ],
    related: ['product-only', 'model-select', 'color', 'detail-page'],
  },

  // ===================== AI 색상 변경 (상품 판매 목적 중심) =====================
  color: {
    key: 'color', slug: '/studio/edit/color', guideSlug: 'color-change', breadcrumb: 'AI 색상 변경',
    title: 'AI 상품 색상 변경 | 컬러 옵션 이미지 만들기',
    description: '상품 색상을 AI가 자연스럽게 변경해 컬러 옵션 이미지를 제작. 사진 한 장으로 여러 색상의 상품 컬러 베리에이션을 만드는 셀러AI 상품 색상 변경.',
    keywords: [
      { term: '상품 색상 변경', intent: 'tool', role: 'primary' },
      { term: '컬러 옵션 이미지', intent: 'tool', role: 'secondary' },
      { term: '상품 컬러 변경', intent: 'tool', role: 'secondary' },
      { term: 'AI 컬러 변경', intent: 'tool', role: 'secondary' },
      { term: '상품 색상 옵션 이미지 만들기', intent: 'informational', role: 'longtail' },
      { term: '컬러 베리에이션', intent: 'tool', role: 'longtail' },
      { term: '색상 옵션 만들기', intent: 'tool', role: 'longtail' },
      { term: '상품 옵션 이미지', intent: 'tool', role: 'longtail' },
    ],
    h1: 'AI 상품 색상 변경', priority: 0.8,
    intro: {
      question: '같은 상품의 색상별 사진, 다시 안 찍고 만들 수 있나요?',
      problem: '한 상품을 여러 색으로 팔 때 색상마다 사진을 찍으려면 시간과 비용이 듭니다. 일부 색은 재고가 없어 아예 촬영을 못 하기도 합니다.',
      solution: '셀러AI 색상 변경은 사진 한 장의 상품 색을 AI가 자연스럽게 바꿔 색상 옵션 이미지를 만듭니다. 재촬영 없이 여러 컬러 베리에이션을 만들어 상품 옵션 이미지를 채울 수 있습니다.',
    },
    steps: [
      { h3: '사진 올리기', desc: '색을 바꿀 상품 사진을 올립니다.' },
      { h3: '색상 선택', desc: '원하는 색을 골라 적용합니다.' },
      { h3: '옵션 이미지 생성', desc: '같은 상품의 색상별 이미지를 만들어 저장합니다.' },
    ],
    beforeAfter: [
      { label: '의류 색상 변경',
        before: { src: '/seo/color/color-apparel-before.webp', alt: '원래 색상 의류 사진', title: '변경 전 — 원래 색상', caption: '변경 전: 원래 색상의 의류' },
        after: { src: '/seo/color/color-apparel-after.webp', alt: '색상 변경된 의류 사진', title: '변경 후 — 다른 색상', caption: '변경 후: 색상만 바꾼 같은 의류' },
        description: '의류의 형태와 질감은 유지하고 색만 바꿔, 재촬영 없이 색상 옵션 이미지를 만들었습니다.' },
      { label: '가방 색상 변경',
        before: { src: '/seo/color/color-bag-before.webp', alt: '원래 색상 가방 사진', title: '변경 전 — 원래 색상', caption: '변경 전: 원래 색상의 가방' },
        after: { src: '/seo/color/color-bag-after.webp', alt: '색상 변경된 가방 사진', title: '변경 후 — 다른 색상', caption: '변경 후: 색상만 바꾼 같은 가방' },
        description: '가방의 소재 질감을 살리면서 색만 바꿔 컬러 옵션을 손쉽게 늘렸습니다.' },
    ],
    useCases: ['의류 색상 옵션', '가방 컬러', '신발 컬러', '소품 색상', '컬러 베리에이션 화보'],
    faq: [
      { q: '사진 속 상품 색상 바꾸는 방법은?', a: '색을 바꿀 상품 사진을 올리고 원하는 색을 고르면, 상품의 형태와 질감은 유지한 채 색상만 자연스럽게 바뀝니다. 사진 한 장으로 여러 색상의 옵션 이미지를 이어서 만들어 상품 컬러 옵션을 채울 수 있습니다.' },
      { q: '색만 바꾸고 모양은 그대로 유지되나요?', a: '상품의 형태와 질감은 유지하고 색상만 자연스럽게 바꿉니다.' },
      { q: '원하는 색을 정확히 지정할 수 있나요?', a: '표준 색상 중에서 골라 적용하며, 여러 색으로 옵션 이미지를 만들 수 있습니다.' },
      { q: '한 장으로 여러 색을 만들 수 있나요?', a: '사진 한 장으로 여러 색상의 옵션 이미지를 이어서 만들 수 있습니다.' },
      { q: '재고가 없는 색도 만들 수 있나요?', a: '실물 없이도 사진의 색을 바꿔 옵션 이미지를 만들 수 있습니다.' },
      { q: '패턴·무늬가 있는 옷도 되나요?', a: '단색 위주로 자연스럽고, 복잡한 무늬는 결과를 확인하며 사용하시길 권합니다.' },
      { q: '가방·신발도 되나요?', a: '의류뿐 아니라 가방·신발·소품의 색상도 바꿀 수 있습니다.' },
      { q: '색이 부자연스럽게 나오면요?', a: '여러 번 생성해 자연스러운 결과를 고를 수 있습니다.' },
      { q: '옵션 이미지로 바로 써도 되나요?', a: '쇼핑몰 색상 옵션 이미지로 사용할 수 있는 형태로 만들어집니다.' },
      { q: '이용권(토큰)은 어떻게 차감되나요?', a: '색상을 변경해 생성할 때 사진 단위로 이용권이 차감됩니다.' },
      { q: '결과는 저장되나요?', a: '생성한 색상 옵션 이미지는 보관함에 저장됩니다.' },
    ],
    related: ['product-only', 'remove-bg', 'model-select', 'detail-page'],
  },

  // ===================== 상세페이지 =====================
  'detail-page': {
    key: 'detail-page', slug: '/studio/detail-page', guideSlug: 'detail-page', breadcrumb: '상세페이지 만들기',
    title: '상세페이지 만들기 | 쿠팡·스마트스토어 자동 제작',
    description: '상품 사진만 올리면 브랜드·특징·사이즈까지 AI가 상세페이지를 자동 제작. 쿠팡·스마트스토어에 바로 쓰는 상세페이지 자동생성 셀러AI.',
    keywords: [
      { term: '상세페이지 제작', intent: 'tool', role: 'primary' },
      { term: '상세페이지 만들기', intent: 'tool', role: 'secondary' },
      { term: '쿠팡 상세페이지', intent: 'tool', role: 'secondary' },
      { term: '스마트스토어 상세페이지', intent: 'tool', role: 'secondary' },
      { term: '상세페이지 만드는 방법', intent: 'informational', role: 'longtail' },
      { term: '상세페이지 자동생성', intent: 'tool', role: 'longtail' },
      { term: '상세페이지 AI', intent: 'tool', role: 'longtail' },
      { term: '쇼핑몰 상세페이지', intent: 'tool', role: 'longtail' },
    ],
    h1: '상세페이지 만들기 (AI 자동 제작)', priority: 0.9,
    intro: {
      question: '쿠팡·스마트스토어 상세페이지, 디자인 없이 만들 수 있나요?',
      problem: '상세페이지는 사진 배치, 문구 작성, 사이즈표, 디자인까지 손이 많이 갑니다. 디자이너에게 맡기면 비용과 시간이 들고, 직접 만들면 통일감을 내기 어렵습니다.',
      solution: '셀러AI 상세페이지 만들기는 상품 사진을 올리면 브랜드 소개, 제품 특징, 사이즈 안내까지 구성해 상세페이지를 자동으로 제작합니다. 쿠팡·스마트스토어에 바로 올릴 수 있는 형태로 만들어집니다.',
    },
    steps: [
      { h3: '사진·정보 입력', desc: '상품 사진과 기본 정보를 입력합니다.' },
      { h3: '구성 자동 생성', desc: 'AI가 브랜드·특징·사이즈 섹션을 구성해 상세페이지를 만듭니다.' },
      { h3: '확인·저장', desc: '내용을 다듬고 이미지로 저장해 쇼핑몰에 올립니다.' },
    ],
    beforeAfter: [
      { label: '패션 상세페이지',
        before: { src: '/seo/detail-page/detail-page-fashion-before.webp', alt: '상품 사진만 있는 상태', title: '제작 전 — 상품 사진', caption: '제작 전: 상품 사진만 있는 상태' },
        after: { src: '/seo/detail-page/detail-page-fashion-after.webp', alt: '완성된 패션 상세페이지', title: '제작 후 — 상세페이지', caption: '제작 후: 구성이 잡힌 상세페이지' },
        description: '상품 사진을 바탕으로 특징·코디 안내가 담긴 패션 상세페이지를 자동으로 구성했습니다.' },
      { label: '뷰티 상세페이지',
        before: { src: '/seo/detail-page/detail-page-beauty-before.webp', alt: '뷰티 상품 사진', title: '제작 전 — 상품 사진', caption: '제작 전: 뷰티 상품 사진' },
        after: { src: '/seo/detail-page/detail-page-beauty-after.webp', alt: '완성된 뷰티 상세페이지', title: '제작 후 — 상세페이지', caption: '제작 후: 구성이 잡힌 상세페이지' },
        description: '성분·사용법 안내가 들어간 뷰티 상세페이지를 일정한 톤으로 만들었습니다.' },
    ],
    useCases: ['패션 상세페이지', '뷰티 상세페이지', '생활용품', '식품', '브랜드 소개 페이지'],
    faq: [
      { q: '쿠팡·스마트스토어 상세페이지 만드는 방법은?', a: '상품 사진과 기본 정보를 입력하면 AI가 브랜드 소개·제품 특징·사이즈 안내 섹션을 구성해 상세페이지를 만들어 줍니다. 내용을 다듬고 이미지로 저장하면 쿠팡·스마트스토어에 바로 올릴 수 있습니다.' },
      { q: '상품 사진만 있으면 상세페이지가 되나요?', a: '사진과 기본 정보를 입력하면 브랜드·특징·사이즈 섹션을 구성해 상세페이지를 만들어 줍니다.' },
      { q: '쿠팡·스마트스토어에 바로 올릴 수 있나요?', a: '쇼핑몰에 올릴 수 있는 이미지 형태로 저장됩니다.' },
      { q: '내용을 직접 수정할 수 있나요?', a: '자동 생성된 문구와 구성을 확인하고 수정할 수 있습니다.' },
      { q: '사이즈표도 만들어 주나요?', a: '사이즈·옵션 안내 섹션을 포함해 구성할 수 있습니다.' },
      { q: '브랜드 톤을 통일할 수 있나요?', a: '글꼴·색상 등을 지정해 여러 상품의 상세페이지 톤을 맞출 수 있습니다.' },
      { q: '외국어 상품도 되나요?', a: '외국어 문구는 번역 기능으로 한글로 바꾼 뒤 상세페이지에 사용할 수 있습니다.' },
      { q: '이미지 길이가 긴 상세페이지도 되나요?', a: '여러 섹션을 이어 붙인 긴 상세페이지로 만들 수 있습니다.' },
      { q: '디자인을 못 해도 되나요?', a: '디자인 작업 없이 구성이 잡힌 상세페이지가 자동으로 만들어집니다.' },
      { q: '이용권(토큰)은 어떻게 차감되나요?', a: '상세페이지를 생성할 때 이용권이 차감되며 플랜별 제공량 안에서 사용합니다.' },
      { q: '결과는 저장되나요?', a: '만든 상세페이지는 보관함에 저장되어 다시 받을 수 있습니다.' },
    ],
    related: ['product-only', 'model-select', 'translate', 'brand'],
  },

  // ===================== AI 브랜드 전속모델 (신뢰도·라이선스·일관성 중심) =====================
  brand: {
    key: 'brand', slug: '/studio/brand', guideSlug: 'brand-model', breadcrumb: 'AI 브랜드 전속모델',
    title: 'AI 브랜드 전속모델 | 브랜드 전용 모델 라이선스',
    description: '내 브랜드만의 AI 전속모델로 일관된 상품 화보를 제작. 독점 모델 라이선스로 경쟁 쇼핑몰과 차별화하는 브랜드 전용 AI 모델 셀러AI.',
    keywords: [
      { term: '브랜드 전속모델', intent: 'brand', role: 'primary' },
      { term: 'AI 전속모델', intent: 'brand', role: 'secondary' },
      { term: '브랜드 전용 모델', intent: 'brand', role: 'secondary' },
      { term: 'AI 모델 라이선스', intent: 'transactional', role: 'secondary' },
      { term: '브랜드 전용 AI 모델 만들기', intent: 'informational', role: 'longtail' },
      { term: '브랜드 화보', intent: 'tool', role: 'longtail' },
      { term: '전속 AI 모델', intent: 'brand', role: 'longtail' },
    ],
    h1: 'AI 브랜드 전속모델', priority: 0.8,
    intro: {
      question: '우리 브랜드만 쓰는 전속 모델, 어떻게 만드나요?',
      problem: '상품마다 모델이 다르면 브랜드 느낌이 흩어집니다. 그렇다고 전속 모델을 계약하면 비용이 크고, 매번 같은 모델로 촬영하기도 어렵습니다.',
      solution: '셀러AI 브랜드관은 우리 브랜드만의 AI 전속 모델을 정해 일관된 상품 화보를 만듭니다. 같은 모델로 시즌마다 컷을 이어가 브랜드 이미지를 통일하고, 경쟁 쇼핑몰과 차별화할 수 있습니다.',
    },
    steps: [
      { h3: '전속 모델 선정', desc: '브랜드에 맞는 AI 모델을 골라 전속 모델로 정합니다.' },
      { h3: '상품 적용', desc: '전속 모델에게 상품을 입혀 화보를 만듭니다.' },
      { h3: '시리즈 제작', desc: '같은 모델로 여러 상품 컷을 이어 브랜드 톤을 통일합니다.' },
    ],
    beforeAfter: [
      { label: '브랜드 전속 모델',
        before: { src: '/seo/brand/brand-brand-before.webp', alt: '모델이 제각각인 상품 사진', title: '도입 전 — 제각각 모델', caption: '도입 전: 상품마다 다른 모델' },
        after: { src: '/seo/brand/brand-brand-after.webp', alt: '동일 전속 모델 화보', title: '도입 후 — 전속 모델', caption: '도입 후: 같은 전속 모델로 통일된 화보' },
        description: '상품마다 달랐던 모델을 하나의 전속 모델로 통일해 브랜드 화보의 일관성을 만들었습니다.' },
      { label: '브랜드 룩북',
        before: { src: '/seo/brand/brand-lookbook-before.webp', alt: '낱장 상품 사진', title: '도입 전 — 낱장 사진', caption: '도입 전: 따로 노는 상품 사진' },
        after: { src: '/seo/brand/brand-lookbook-after.webp', alt: '전속 모델 룩북 화보', title: '도입 후 — 룩북', caption: '도입 후: 전속 모델 룩북 화보' },
        description: '전속 모델로 시즌 룩북을 구성해 브랜드 톤이 이어지는 화보를 만들었습니다.' },
    ],
    useCases: ['여성 의류 브랜드', '남성 의류 브랜드', '키즈 브랜드', '액세서리 브랜드', '시즌 룩북'],
    faq: [
      { q: '브랜드 전용 AI 전속모델 만드는 방법은?', a: '브랜드 콘셉트에 맞는 AI 모델을 골라 전속 모델로 정하고, 그 모델에게 상품을 입혀 화보를 만듭니다. 같은 전속 모델로 여러 상품 컷을 이어가면 브랜드 톤이 일관되게 유지됩니다.' },
      { q: '전속 모델을 정해두면 계속 같은 얼굴이 나오나요?', a: '정해둔 전속 모델로 여러 상품 컷을 이어 만들어 일관된 얼굴·분위기를 유지합니다.' },
      { q: '구매한 전속 모델은 다른 브랜드도 쓸 수 있나요?', a: '구매한 전속 모델은 해당 브랜드의 독점 사용을 전제로 합니다. 같은 모델이 경쟁 쇼핑몰에 쓰이지 않도록 차별화하는 것이 목적입니다.' },
      { q: '실제 모델 계약 없이 가능한가요?', a: 'AI 전속 모델이라 모델 계약이나 초상권 부담 없이 브랜드 전용으로 사용할 수 있습니다.' },
      { q: '브랜드마다 다른 모델을 만들 수 있나요?', a: '브랜드 콘셉트에 맞는 모델을 골라 전속으로 지정할 수 있습니다.' },
      { q: '시즌마다 같은 모델로 이어갈 수 있나요?', a: '같은 전속 모델로 시즌별 화보를 이어 만들 수 있습니다.' },
      { q: '룩북 제작에도 쓸 수 있나요?', a: '전속 모델로 여러 코디 컷을 모아 룩북을 구성할 수 있습니다.' },
      { q: '키즈 브랜드도 되나요?', a: '여성·남성·키즈 모델을 전속으로 지정할 수 있습니다.' },
      { q: '경쟁사와 차별화에 도움이 되나요?', a: '우리 브랜드만의 모델로 통일감을 줘 다른 쇼핑몰과 구분되는 이미지를 만듭니다.' },
      { q: '다른 기능과 함께 쓸 수 있나요?', a: '착용샷·상세페이지 기능과 연계해 브랜드 화보부터 상세페이지까지 이어 만들 수 있습니다.' },
      { q: '이용권(토큰)은 어떻게 차감되나요?', a: '화보 이미지를 생성할 때 사진 단위로 이용권이 차감됩니다.' },
      { q: '결과는 저장되나요?', a: '생성한 브랜드 화보는 보관함에 저장됩니다.' },
    ],
    related: ['model-select', 'dressed', 'detail-page', 'product-only'],
  },

  // ===================== 요금제 =====================
  pricing: {
    key: 'pricing', slug: '/studio/pricing', breadcrumb: '요금제·가격',
    title: '요금제·가격 | AI 상품사진·상세페이지 이용권',
    description: '셀러AI 월·연 구독 요금제와 플랜별 토큰·기능 안내. AI 상품사진·모델컷·상세페이지를 합리적 가격에 쓰는 이용권 가격표 셀러AI.',
    keywords: [
      { term: 'AI 상품사진 가격', intent: 'transactional', role: 'primary' },
      { term: '상세페이지 제작 비용', intent: 'transactional', role: 'secondary' },
      { term: 'AI 상세페이지 가격', intent: 'transactional', role: 'secondary' },
      { term: '셀러AI 요금제', intent: 'brand', role: 'secondary' },
      { term: 'AI 상품사진·상세페이지 비용 비교', intent: 'comparison', role: 'longtail' },
      { term: 'AI 모델컷 가격', intent: 'transactional', role: 'longtail' },
      { term: '상품사진 AI 가격', intent: 'transactional', role: 'longtail' },
    ],
    h1: '셀러AI 요금제·가격', priority: 0.7,
    intro: {
      question: 'AI 상품사진·상세페이지, 비용이 얼마나 드나요?',
      problem: '상품 촬영이나 상세페이지 외주는 건당 비용이 들고, 상품이 늘수록 부담이 커집니다. 어떤 도구가 내 판매 규모에 맞는지 가늠하기도 어렵습니다.',
      solution: '셀러AI는 월·연 구독으로 플랜별 이용권 안에서 AI 상품사진·모델컷·상세페이지·번역을 사용합니다. 판매 규모에 맞는 플랜을 골라 필요한 만큼 합리적으로 운영할 수 있습니다.',
    },
    useCases: ['1인 셀러', '소규모 쇼핑몰', '브랜드 운영', '대량 상품 등록'],
    faq: [
      { q: '무료로 시작할 수 있나요?', a: '가입 후 제공되는 이용권으로 주요 기능을 먼저 사용해 볼 수 있습니다.' },
      { q: '플랜은 어떻게 나뉘나요?', a: '제공 이용권과 사용 가능한 기능에 따라 여러 단계의 플랜으로 나뉩니다.' },
      { q: '이용권(토큰)은 어떤 기준으로 차감되나요?', a: '이미지를 생성·변환·완료할 때 사진 단위로 이용권이 차감됩니다.' },
      { q: '월 구독과 연 구독은 무엇이 다른가요?', a: '연 구독은 월 구독보다 장기 사용 시 더 합리적으로 이용할 수 있습니다.' },
      { q: '플랜을 중간에 바꿀 수 있나요?', a: '사용 중 더 높은 플랜으로 변경하거나 조정할 수 있습니다.' },
      { q: '이용권을 다 쓰면 어떻게 되나요?', a: '다음 결제 주기에 이용권이 다시 제공되며, 필요 시 상위 플랜으로 변경할 수 있습니다.' },
      { q: '결제 수단은 무엇이 있나요?', a: '정기결제(카드)로 월·연 구독을 이용할 수 있습니다.' },
      { q: '세금계산서 발행이 되나요?', a: '사업자의 경우 결제 내역에 대한 증빙을 받을 수 있습니다.' },
      { q: '해지하면 바로 중단되나요?', a: '해지하면 다음 결제부터 청구되지 않으며, 남은 기간은 그대로 사용할 수 있습니다.' },
      { q: '만든 이미지는 해지 후에도 쓸 수 있나요?', a: '이미 만들어 내려받은 이미지는 계속 사용할 수 있습니다.' },
    ],
    related: ['product-only', 'translate', 'detail-page', 'model-select'],
  },
}

// ── 검색 제외(개인 콘텐츠) — order에 넣지 않아 sitemap에서도 자동 제외 ──
FEATURES.gallery = {
  key: 'gallery', slug: '/studio/gallery', breadcrumb: '보관함',
  title: '보관함', description: '내가 만든 이미지 보관함',
  keywords: [], h1: '보관함', noindex: true,
}

export const sellerai: ServiceSeoConfig = {
  key: 'sellerai',
  brandName: '셀러AI',
  siteBase: SELLERAI_SITE,
  locale: 'ko_KR',
  order: ORDER,
  features: FEATURES,
}
